repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: bun x prettier --write --ignore-unknown
        language: system
        types_or: [ts, tsx, javascript, jsx, json, yaml, markdown, css, html]
      - id: typecheck
        name: typecheck
        entry: bun x tsc --noEmit
        language: system
        pass_filenames: false
        types_or: [ts, tsx]
      - id: test
        name: test
        entry: bun test
        language: system
        pass_filenames: false
        types_or: [ts, tsx]
