name: GitHub release

on:
  workflow_call:

permissions:
  contents: write

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="$(jq -r .version package.json)"
          gh release create "v$VERSION" \
            --title "v$VERSION" \
            --generate-notes
